const W: string[] = [
  "Lifegain",
  "Equipment",
  "Aura",
  "Artifact",
  //"Stax",
  //"Hatebear",
  "Tokens",
  "Flying",
  "Keywords",
  "Soldier Tokens",
  "Sacrifice",
  "Blink",
  "Planeswalker",
  "Cantrip",
  "Historic",
  "Anthem",
  "Cheerios",
  "+1/+1 Counter",
  "Reanimator",
  "Angel Tribal",
  "Human Tribal",
  "Soldier Tribal",
  "Spirit Tribal",
  "Samurai Tribal",
  "Cat Tribal",
  "Fox Tribal",
  "Cleric Tribal"
];

const U: string[] = [
  "Artifact",
  "Cantrip",
  "Wheel",
  //"Spellslinger",
  //"Counterspell",
  //"Storm",
  //"Persistent Petitioner",
  "Mill",
  "Topdeck",
  "Toughness",
  "Bounce",
  "Cheerios",
  "Clone",
  "Flying",
  "Vehicle",
  "Equipment",
  "Theft",
  "Sea Creatures",
  //"Extra Turns",
  "Big Mana",
  "Aura",
  "Infect",
  "Group Hug",
  "Planeswalker",
  //"Wizard Tribal",
  "Merfolk Tribal",
  "Shapeshifter Tribal",
  "Spirit Tribal"
];

const B: string[] = [
  "Aristocrat",
  "Lifegain",
  "Discard",
  "Rat Colony",
  "Sacrifice",
  "Zombie Tokens",
  //"Relentless Rat",
  //"Shadowborn Apostle",
  "Reanimator",
  "Infect",
  "Mill",
  "Equipment",
  "Graveyard",
  "Ad Nauseam",
  "Wheel",
  "Artifact",
  "Treasure",
  "Voltron",
  "Planeswalker",
  "Zombie Tribal",
  "Vampire Tribal",
  "Rat Tribal",
  "Demon Tribal",
  "Phyrexian Tribal",
  "Spirit Tribal"
];

const R: string[] = [
  //"Treasure",
  "Burn",
  "Artifact",
  "Goblin Tokens",
  "Equipment",
  "Extra Combat",
  "Planeswalker",
  "Wheel",
  "Tokens",
  "Chaos",
  "Cheerios",
  "Spellslinger",
  "Sacrifice",
  "Group Slug",
  "Voltron",
  "Forced Combat",
  //"Storm",
  "Theft",
  "Discard",
  "Card Draw",
  "Cantrip",
  "Pingers",
  "Goblin Tribal",
  "Dragon Tribal",
  "Dwarf Tribal",
  "Elemental Tribal"
];

const G: string[] = [
  "+1/+1 Counter",
  "Deathtouch",
  "Sacrifice",
  "Infect",
  "Aura",
  "Cantrip",
  "Fight",
  "Voltron",
  "Lands",
  "Equipment",
  "Stompy",
  "Pod",
  "Landfall",
  "Legends",
  "Tokens",
  "Ramp",
  "Big Mana",
  "Wheel",
  "Saproling Tokens",
  "Cheerios",
  //"Storm",
  "Card Draw",
  "Elf Tribal",
  "Bear Tribal",
  "Hydra Tribal",
  "Druid Tribal",
  "Snake Tribal",
  "Spirit Tribal",
  "Eldrazi Tribal"
];

const C: string[] = [
  "Artifact",
  "Big Mana",
  "Sacrifice",
  "Equipment",
  "Eldrazi Tribal"
];

const WU: string[] = [
  "Vehicle",
  "Foretell",
  "Blink",
  "Flying",
  "Wheel",
  "Aura",
  //"Stax",
  "Topdeck",
  "Artifact",
  "Equipment",
  //"Spellslinger",
  "Unnatural",
  "Cantrip",
  "Historic",
  "Clone",
  "Planeswalker",
  "Reanimator",
  //"Hatebear",
  "Exile",
  "Voltron",
  //"Counterspell",
  //"Flash",
  "Mill",
  "Legends",
  //"Extra Turns",
  "Spirit Tribal",
  "Bird Tribal",
  "Dragon Tribal",
  "Sphinx Tribal"
];

const UB: string[] = [
  "Ninjutsu",
  "Zombie Tokens",
  "Mill",
  "Exile",
  "Toughness",
  "Artifact",
  "Aristocrat",
  "Topdeck",
  "Self-Mill",
  "Clone",
  "Sacrifice",
  "Discard",
  "Snow",
  "Graveyard",
  "Reanimator",
  "Infect",
  "-1/-1 Counter",
  "Stompy",
  //"Treasure",
  "Gyruda Companion",
  "Cantrip",
  "Wheel",
  //"Spellslinger",
  "Theft",
  "Party",
  "Zombie Tribal",
  "Rogue Tribal",
  "Horror Tribal",
  "Ninja Tribal",
  "Faerie Tribal"
];

const BR: string[] = [
  "Treasure",
  "Madness",
  "Exile",
  "Sacrifice",
  "Aristocrat",
  "Discard",
  "Forced Combat",
  "Graveyard",
  "Wheel",
  "Reanimator",
  "Chaos",
  "Party",
  "Obosh Companion",
  "Burn",
  "Theft",
  "Artifact",
  "Curse",
  "Lifegain",
  //"Relentless Rat",
  //"Rat Colony",
  "Equipment",
  "Big Mana",
  "Planeswalker",
  "Vampire Tribal",
  "Goblin Tribal",
  "Demon Tribal",
  "Minotaur Tribal",
  "Dragon Tribal"
];

const RG: string[] = [
  "+1/+1 Counters",
  "Enchantment",
  "Lifegain",
  "Tokens",
  "Aura",
  "Kaheera Companion",
  "Equipment",
  //"Hatebear",
  "Landfall",
  "Populate",
  "Historic",
  "Pod",
  //"Stax",
  "Legends",
  //"Group Hug",
  "Blink",
  "Lands",
  "Sacrifice",
  //"Treasure",
  "Human Tokens",
  "Human Tribal",
  "Cat Tribal",
  "Elf Tribal",
  "Angel Tribal",
  "Unicorn Tribal",
  "Elephant Tribal"
];

const GW: string[] = [
  "+1/+1 Counters",
  "Enchantment",
  "Lifegain",
  "Tokens",
  "Auras",
  "Kaheera Companion",
  "Equipment",
  //"Hatebear",
  "Landfall",
  "Populate",
  "Historic",
  "Pod",
  //"Stax",
  "Legends",
  "Group Hug",
  "Blink",
  "Lands",
  "Sacrifice",
  //"Treasure",
  "Human Tokens",
  "Human Tribal",
  "Cat Tribal",
  "Elf Tribal",
  "Angel Tribal",
  "Unicorn Tribal",
  "Elephant Tribal"
];

const WB: string[] = [
  "Lifegain",
  "Aristocrat",
  "Aura",
  "Tokens",
  "Party",
  //"Shadowborn Apostle",
  "Sacrifice",
  "+1/+1 Counters",
  "Reanimator",
  //"Rat Colony",
  "Equipment",
  //"Stax",
  "Blink",
  //"Hatebear",
  "Lurrus Companion",
  "Pillow Fort",
  //"Treasure",
  "Historic",
  "Unnatural",
  "Spirit Tokens",
  "Cleric Tribal",
  "Vampire Tribal",
  "Angel Tribal",
  "Human Tribal",
  "Demon Tribal",
  "Zombie Tribal"
];

const UR: string[] = [
  "Spellslinger",
  "Wheel",
  //"Treasure",
  "Artifact",
  "Spell Copy",
  "Chaos",
  "Cantrip",
  "Discard",
  "Big Mana",
  "Cheerios",
  "Forced Combat",
  "Clone",
  //"Storm",
  "X Spell",
  "Topdeck",
  "Planeswalker",
  "Polymorph",
  "Exile",
  //"Extra Turns",
  "Pingers",
  "Foretell",
  //"Wizard Tribal",
  "Pirate Tribal",
  "Dragon Tribal",
  "Myr Tribal"
];

const BG: string[] = [
  "Lifegain",
  "Aristocrat",
  "Sacrifice",
  "Token",
  "Saproling Token",
  "-1/-1 Counters",
  "+1/+1 Counters",
  "Graveyard",
  "Planeswalker",
  "Pod",
  "Deathtouch",
  "Lands",
  "Mill",
  "Artifact",
  //"Treasure",
  "Dredge",
  "Stompy",
  "Reanimator",
  "Infect",
  //"Rat Colony",
  "Toughness",
  "Elf Tokens",
  "Self-Mill",
  "Equipment",
  "Relentless Rat",
  "Insect Tokens",
  "Voltron",
  "Elf Tribal",
  "Insect Tribal",
  "Fungus Tribal",
  "Phyrexian Tribal",
  "Zombie Tribal",
  "Skeleton Tribal",
  "Ooze Tribal"
];

const RW: string[] = [
  "Equipment",
  "Artifact",
  "Sunforger",
  "Vehicle",
  "Burn",
  "Tokens",
  "Extra Combats",
  "Theft",
  "Aura",
  "Historic",
  //"Treasure",
  "Keywords",
  //"Spellslinger",
  "Sacrifice",
  "Exile",
  "Soldier Tokens",
  "Cheerios",
  "Blink",
  "Voltron",
  "Forced Combat",
  "Dwarf Tribal",
  "Angel Tribal",
  "Human Tribal",
  "Soldier Tribal",
  "Giant Tribal",
  "Samurai Tribal",
  "Dragon Tribal",
  "Spirit Tribal",
  "Knight Tribal"
];

const GU: string[] = [
  "Tokens",
  "+1/+1 Counters",
  "Lands",
  "Pod",
  "Clue",
  "Big Mana",
  "Sea Creatures",
  "Clone",
  "Topdeck",
  "Mill",
  "Cantrip",
  "Infect",
  "Landfall",
  //"Extra Turns",
  "Wheel",
  "Spellslinger",
  "Card Draw",
  "Keruga Companion",
  "Snow",
  //"Storm",
  "Artifact",
  "Planeswalker",
  "X Spell",
  "Bounce",
  "Group Hug",
  "Self-Mill",
  "Merfolk Tribal",
  "Elf Tribal",
  "Eldrazi Tribal",
  "Phyrexian Tribal"
];

const WUB: string[] = [
  "Lifegain",
  "Artifact",
  "Wheel",
  "Unnatural",
  "Zombie Tokens",
  "Topdeck",
  "Blink",
  "Reanimator",
  "Politics",
  "Aura",
  "Vehicle",
  "Discard",
  "Enchantment",
  "Planeswalker",
  "Cycling",
  "Equipment",
  "Flying",
  "Aristocrat",
  //"Stax",
  "Cantrip",
  "Treasure",
  "Theft",
  "Sacrifice",
  "Snow",
  "Exile",
  "Graveyard",
  "Clue",
  "Clone",
  "Curse",
  "Zombie Tribal",
  "Sphinx Tribal"
];

const UBR: string[] = [
  "Wheel",
  "Spellslinger",
  //"Treasure",
  "Clone",
  "Artifact",
  "Theft",
  "Aristocrat",
  "Planeswalker",
  "Sacrifice",
  "Spell Copy",
  "Discard",
  "Exile",
  "Zombie Tokens",
  "Mill",
  "Reanimator",
  "Chaos",
  "Graveyard",
  "Obosh Companion",
  "Big Mana",
  "Pirate Tribal",
  "Wizard Tribal",
  "Vampire Tribal",
  "Zombie Tribal",
  "Dragon Tribal",
  "Rogue Tribal"
];

const BRG: string[] = [
  "Sacrifice",
  //"Treasure",
  "Lands",
  "Aristocrat",
  "Forced Combat",
  "Pod",
  "Primal Surge",
  "Power",
  "+1/+1 Counters",
  "Land Destruction",
  "X Spell",
  "Fight",
  "Graveyard",
  "Stompy",
  "Tokens",
  "Infect",
  "Planeswalkers",
  "Obosh Companion",
  //"Shadowborn Apostle",
  "Big Mana",
  "Goblin Tokens",
  "Dragon Tribal",
  "Goblin Tribal",
  "Elf Tribal",
  "Hydra Tribal"
];

const RGW: string[] = [
  "Tokens",
  "Aura",
  "Landfall",
  "Populate",
  "Pod",
  "Lands",
  "Kaheera Companion",
  //"Treasure",
  "Equipment",
  "Big Mana",
  "+1/+1 Counters",
  "Forced Combat",
  "Enrage",
  //"Hatebear",
  "Fight",
  "Primal Surge",
  "Enchantment",
  "Legends",
  "Extra Combats",
  "Dinosaur Tribal",
  "Cat Tribal",
  "Dragon Tribal",
  "Shapeshifter Tribal",
  "Beast Tribal",
  "Angel Tribal",
  "Wurm Tribal",
  "Elf Tribal",
  "Human Tribal",
  "Werewolf Tribal"
];

const GWU: string[] = [
  "Toughness",
  "Aura",
  "Enchantment",
  "Equipment",
  "Blink",
  "+1/+1 Counters",
  "Pod",
  //"Stax",
  "Voltron",
  "Planeswalkers",
  "Tokens",
  //"Hatebear",
  "Artifact",
  "Lands",
  "Landfall",
  "Cantrip",
  "Clue",
  "Infect",
  "Primal Surge",
  "Bird Tribal",
  "Merfolk Tribal"
];

const WBG: string[] = [
  "+1/+1 Counters",
  "Pod",
  "Toughness",
  "Lifegain",
  "Aristocrat",
  "Historic",
  "Graveyard",
  "Legends",
  "Saproling Tokens",
  "Tokens",
  "Sacrifice",
  //"Hatebear",
  "Reanimator",
  "Enchantment",
  "Keywords",
  "Planeswalker",
  "Mill",
  "Deathtouch",
  "Umori Companion",
  //"Shadowborn Apostle",
  "Treefolk Tribal",
  "Elf Tribal",
  "Human Tribal",
  "Spirit Tribal"
];

const URW: string[] = [
  "Spellslinger",
  "Cycling",
  "Wheel",
  "Equipment",
  "Discard",
  "Chaos",
  "Planeswalkers",
  "Artifact",
  "Vehicle",
  "Cantrip",
  "Prowess",
  "Sunforger",
  "Voltron",
  "Tokens",
  "Aura",
  "Spell Copy",
  "Blink",
  //"Treasure",
  //"Storm",
  "Topdeck",
  "Flying",
  //"Stax",
  "Monk Tribal",
  "Spirit Tribal"
];

const BGU: string[] = [
  "Pod",
  "Sacrifice",
  "Lands",
  "Mutate",
  "Snow",
  "Mill",
  "Enchantment",
  "+1/+1 Counter",
  "Graveyard",
  "Infect",
  "Clone",
  "Landfall",
  "Ninjutsu",
  "Artifact",
  "Primal Surge",
  "Self-Mill",
  "Dredge",
  "Zombie Tokens",
  //"Persistent Petitioner",
  "Planeswalkers",
  "Cantrip",
  "Gyruda Companion",
  "Ooze Tribal",
  "Zombie Tribal",
  "Phyrexian Tribal",
  "Elf Tribal",
  "Ninja Tribal",
  "Shapeshifter Tribal",
  "Eldrazi Tribal"
];

const RWB: string[] = [
  "Equipment",
  "Lifegain",
  "Flying",
  //"Treasure",
  "Sacrifice",
  "Tokens",
  "Aristocrat",
  "Sunforger",
  "Curse",
  "Artifact",
  "Extra Combats",
  "Reanimator",
  "Legends",
  "Aura",
  "Obosh Companion",
  "Forced Combat",
  "Voltron",
  "Vampire Tribal",
  "Knight Tribal",
  "Human Tribal",
  "Angel Tribal",
  "Samurai Tribal",
  "Warrior Tribal"
];


const GUR: string[] = [
  "Spell Copy",
  "Wheel",
  "Pod",
  "Cascade",
  "Spellslinger",
  "Lands",
  "Mutate",
  "Clone",
  "Treasure",
  "Polymorph",
  "+1/+1 Counters",
  "Big Mana",
  "Chaos",
  "Landfall",
  "Theft",
  "Keruga Companion",
  "Primal Surge",
  "Tokens",
  "Cantrip",
  "Topdeck",
  "Energy",
  "Sacrifice",
  "Dragon Tribal",
  "Elemental Tribal",
  "Wizard Tribal",
  "Shapeshifter Tribal"
];

const WUBR: string[] = [
  "Artifact",
  //"Treasure",
  "Vehicle",
  "Sacrifice",
  "Equipment",
  "Wheel",
  "Blink"
];

const UBRG: string[] = [
  "Pod",
  "Wheel",
  "Lands",
  "Clone",
  "Spellslinger",
  //"Treasure",
  "Big Mana",
  "X Spell"
];

const BRGW: string[] = [
  "Pod",
  "Tokens",
  "Saproling Tokens",
  "Aristocrat",
  "+1/+1 Counters",
  "Equipment",
  //"Treasure",
  "Human Tribal"
];

const RGWU: string[] = [
  "Lands",
  "Landfall",
  "Pod",
  "Clue",
  "Tokens",
  "Artifact"
];

const GWUB: string[] = [
  "+1/+1 Counters",
  "Pod",
  "Lifegain",
  "Enchantment",
  "Merfolk Tribal"
];

const WUBRG: string[] = [
  "Enchantment",
  "Lands",
  "Pod",
  "Planeswalker",
  "Big Mana",
  "Legends",
  "Historic",
  "Devotion",
  "Party",
  "Spellslinger",
  "Mutate",
  "Jegantha Companion",
  //"Treasure",
  "Snow",
  "Artifact",
  "Cycling",
  "Politics",
  "Sacrifice",
  "Group Hug",
  "Blink",
  "Cascade",
  "+1/+1 Counters",
  "Tokens",
  "Sagas",
  "Chaos",
  "Aura",
  "Kaheera Companion",
  "Curse",
  "Wheel",
  "Discard",
  "Primal Surge",
  "Exile",
  "Clone",
  "Cantrip",
  "Lifegain",
  "Forced Combat",
  "Equipment",
  "Pillow Fort",
  "Eldrazi Token",
  "Reanimator",
  "Landfall",
  "Polymorph",
  "Umori Companion",
  "Ramp",
  "Toughness",
  "Zirda Companion",
  "Anthem",
  "Dragon Tribal",
  "Sliver Tribal",
  "Shapeshifter Tribal",
  "God Tribal",
  "Elemental Tribal",
  "Eldrazi Tribal",
  "Ally Tribal",
  "Human Tribal",
  "Spirit Tribal",
  "Angel Tribal",
  "Hydra Tribal",
  "Myr Tribal",
  "Phyrexian Tribal",
  "Wizard Tribal"
];

export const subthemes = {
  W: W,
  U: U,
  B: B,
  R: R,
  G: G,
  C: C,
  WU: WU,
  UB: UB,
  BR: BR,
  RG: RG,
  GW: GW,
  WB: WB,
  UR: UR,
  BG: BG,
  RW: RW,
  GU: GU,
  WUB: WUB,
  UBR: UBR,
  BRG: BRG,
  RGW: RGW,
  GWU: GWU,
  WBG: WBG,
  URW: URW,
  BGU: BGU,
  RWB: RWB,
  GUR: GUR,
  WUBR: WUBR,
  UBRG: UBRG,
  BRGW: BRGW,
  RGWU: RGWU,
  GWUB: GWUB,
  WUBRG: WUBRG
}
