export const top_saved =[
  "Atraxa, Praetors' Voice",
  "Yuriko, the Tiger's Shadow",
  "Kenrith, the Returned King",
  "Lathril, Blade of the Elves",
  "The Ur-Dragon",
  "Edgar Markov",
  "Korvold, Fae-Cursed King",
  "Prosper, Tome-Bound",
  "Omnath, Locus of Creation",
  "Wilhelt, the Rotcleaver",
  "Muldrotha, the Gravetide",
  "Kaalia of the Vast",
  "Sisay, Weatherlight Captain",
  "Krenko, Mob Boss",
  "Meren of Clan Nel Toth",
  "Esika, God of the Tree",
  "Isshin, Two Heavens as One",
  "Alela, Artful Provocateur",
  "Chatterfang, Squirrel General",
  "Breya, Etherium Shaper",
  "Arcades, the Strategist",
  "Queen Marchesa",
  "Anowon, the Ruin Thief",
  "Sythis, Harvest's Hand",
  "Yarok, the Desecrated",
  "Osgir, the Reconstructor",
  "Gishath, Sun's Avatar",
  "Niv-Mizzet, Parun",
  "Go-Shintai of Life's Origin",
  "Liesa, Shroud of Dusk",
  "Animar, Soul of Elements",
  "Zaxara, the Exemplary",
  "Tovolar, Dire Overlord",
  "Kykar, Wind's Fury",
  "Veyran, Voice of Duality",
  "Kess, Dissident Mage",
  "Teysa Karlov",
  "Oloro, Ageless Ascetic",
  "Shorikai, Genesis Engine",
  "Nekusar, the Mindrazer",
  "Feather, the Redeemed",
  "Atla Palani, Nest Tender",
  "Orvar, the All-Form",
  "Lord Windgrace",
  "K'rrik, Son of Yawgmoth",
  "Aesi, Tyrant of Gyre Strait",
  "Miirym, Sentinel Wyrm",
  "The Scarab God",
  "Kalamax, the Stormsire",
  "Najeela, the Blade-Blossom",
  "Chulane, Teller of Tales",
  "Urza, Lord High Artificer",
  "Rin and Seri, Inseparable",
  "Brago, King Eternal",
  "Zur the Enchanter",
  "Morophon, the Boundless",
  "Obeka, Brute Chronologist",
  "Syr Gwyn, Hero of Ashvale",
  "Sefris of the Hidden Ways",
  "Hinata, Dawn-Crowned",
  "Jodah, Archmage Eternal",
  "Satoru Umezawa",
  "Marchesa, the Black Rose",
  "Volo, Guide to Monsters",
  "Tergrid, God of Fright",
  "Dina, Soul Steeper",
  "Magda, Brazen Outlaw",
  "Galea, Kindler of Hope",
  "Kinnan, Bonder Prodigy",
  "Marrow-Gnawer",
  "Adrix and Nev, Twincasters",
  "Jhoira, Weatherlight Captain",
  "Kozilek, the Great Distortion",
  "Tasigur, the Golden Fang",
  "The First Sliver",
  "Tuvasa the Sunlit",
  "Aminatou, the Fateshifter",
  "Varina, Lich Queen",
  "Winota, Joiner of Forces",
  "Xyris, the Writhing Storm",
  "Extus, Oriq Overlord",
  "Omnath, Locus of Rage",
  "Nethroi, Apex of Death",
  "Elsha of the Infinite",
  "Araumi of the Dead Tide",
  "Anje Falkenrath",
  "The Gitrog Monster",
  "Torbran, Thane of Red Fell",
  "Alesha, Who Smiles at Death",
  "Haldan, Avid Arcanist // Pako, Arcane Retriever",
  "Sliver Overlord",
  "Admiral Beckett Brass",
  "Kynaios and Tiro of Meletis",
  "Ramos, Dragon Engine",
  "Riku of Two Reflections",
  "Codie, Vociferous Codex",
  "Giada, Font of Hope",
  "Ardenn, Intrepid Archaeologist // Rograkh, Son of Rohgahh",
  "Nicol Bolas, the Ravager",
  "Narset, Enlightened Master"
]
